//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talent.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEntry
    {
        public int Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Thread { get; set; }
        public string Level { get; set; }
        public string LogType { get; set; }
        public string Marsegory { get; set; }
        public string Message { get; set; }
        public string Exception { get; set; }
        public string AppliMarsionName { get; set; }
        public string MachineName { get; set; }
        public string UserName { get; set; }
        public string Version { get; set; }
        public string EntityType { get; set; }
        public string Data { get; set; }
    }
}
