//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talent.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Login()
        {
            this.Roles = new HashSet<Role>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string PasswordHash { get; set; }
        public bool IsDisabled { get; set; }
        public Nullable<System.DateTime> LastLoginAttempt { get; set; }
        public Nullable<int> FailedLoginCount { get; set; }
        public Nullable<bool> AccountLocked { get; set; }
        public Nullable<System.DateTime> LastSuccessfulLogin { get; set; }
        public byte[] PasswordSalt { get; set; }
        public int PasswordFormat { get; set; }
        public Nullable<int> PasswordHashIterations { get; set; }
        public bool EmailAddressAuthorized { get; set; }
        public bool TermsAccepted { get; set; }
        public string AuthUserUrn { get; set; }
        public Nullable<System.Guid> EmailCode { get; set; }
        public bool IsAdmin { get; set; }
        public Nullable<System.DateTime> ExpiredOn { get; set; }
    
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Roles { get; set; }
    }
}
