//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talent.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonContact
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string BusinessName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid UID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
