//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talent.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonSkill
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public string Skill { get; set; }
        public string ExperienceLevel { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
