//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talent.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonLanguage
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public string Language { get; set; }
        public string LanguageLevel { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
