//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talent.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonServiceTag
    {
        public int Id { get; set; }
        public int ServiceID { get; set; }
        public string Text { get; set; }
        public Nullable<int> TagIndex { get; set; }
    
        public virtual PersonService PersonService { get; set; }
    }
}
