//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talent.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.PersonAvailabilities = new HashSet<PersonAvailability>();
            this.PersonContacts = new HashSet<PersonContact>();
            this.PersonDescriptions = new HashSet<PersonDescription>();
            this.PersonDocuments = new HashSet<PersonDocument>();
            this.PersonEducations = new HashSet<PersonEducation>();
            this.PersonLanguages = new HashSet<PersonLanguage>();
            this.PersonServices = new HashSet<PersonService>();
            this.PersonSkills = new HashSet<PersonSkill>();
            this.PersonSkillListings = new HashSet<PersonSkillListing>();
        }
    
        public int Id { get; set; }
        public System.Guid UID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> GenderId { get; set; }
        public string Phone { get; set; }
        public string MobilePhone { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string DialCode { get; set; }
        public string CountryCode { get; set; }
        public int VerifiMarsionLevel { get; set; }
        public string MobileCode { get; set; }
        public Nullable<System.DateTime> MobileCodeGenerated { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsVerifyMobile { get; set; }
        public Nullable<int> TradeNumber { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public Nullable<int> TrustedNumber { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Login Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonAvailability> PersonAvailabilities { get; set; }
        public virtual PersonAddress PersonAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonContact> PersonContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonDescription> PersonDescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonDocument> PersonDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonEducation> PersonEducations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonLanguage> PersonLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonService> PersonServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonSkill> PersonSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonSkillListing> PersonSkillListings { get; set; }
    }
}
